# Generated by Django 5.0.4 on 2024-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0001_initial'),
        ('users', '0003_currentstates_mvz_positioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='baseposition',
            name='training_requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='base_positions', to='training_center.educationmethod', verbose_name='Обязательное обучение'),
        ),
    ]
