# Generated by Django 5.0.4 on 2024-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastname',
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employes_photo', verbose_name='Фото'),
        ),
    ]
